### ISSUE TITLE
Where is the Pre-trained model?

### ISSUE THREAD

**Issue by mprgseo** [hughw19/NOCS_CVPR2019#1]
I'm in the process of executing the sample code, but I don't know where to place the trained model.
I'd appreciate it if you could answer my questions.

**Comment by hughw19** [comment]
You can specify the path of the trained model in detect_eval.py from line 219 - line 225. You will load the model in line 279.

**Comment by hughw19** [comment]
I just provide the download link for some pretrained weight. Let me know if this solve your problem.
