### ISSUE TITLE
How to obtain pose GTs for each objects?

### ISSUE THREAD

**Issue by zj-dong** [hughw19/NOCS_CVPR2019#10]
Hi He,

I find that you only provide camera poses, but not poses for each object. How could I obtain the 6D pose for each object?

**Comment by hughw19** [comment]
For CAMERA validation and Real test set, we provide the ground truths in http://download.cs.stanford.edu/orion/nocs/gts.zip. You can download, unzip, and put it under data/. Then you can run detect_eval.py to use the ground truths. 

For all data, we provide ground truth NOCS map which can be used with aligning.py to get ground truth pose.

**Comment by hughw19** [comment]
BTW, there is no camera pose problem in this data. We are interested in the object pose in the camera reference frame. In this sense, the camera is always canonical.

**Comment by zj-dong** [comment]
Thanks for your answers. If there exists occlusions, are the aligning results right?

**Comment by hughw19** [comment]
Unless there is only a few points (< 10), aligning using ground truth NOCS will give you an accurate pose.

Best,
He

**Comment by zj-dong** [comment]
Thanks for your replying. For the ground truth pose, what is the difference between old and normal pose?

**Comment by hughw19** [comment]
Do you mean the difference between like "results_val_00753_0008_old.pkl" and "results_val_00753_0008.pkl" under gts/val? I fixed some errors in *_old.pkl, so you can just ignore them.

**Comment by taeyeop-lee** [comment]
@zj-dong, @hughw19 Can you share the camera pose labels for real(train/test) with me (taeyeop.trevor@gmail.com)?? 
It would be really appreciated!!
