### ISSUE TITLE
3D object meshes without texture

### ISSUE THREAD

**Issue by diarodriguezva** [hughw19/NOCS_CVPR2019#11]
Hi, 
I would like to use the 3D meshes from the dataset, but I have noticed that the textures (.mtl files) of the real objects ('real_test' and 'real_train' folders) are missing, only the .obj files are provided. Is it possible you also share the textures?

**Comment by hughw19** [comment]
The texture will not be good since all objects are manually scanned. The mesh is also not watertight.

I suggest you not to use mesh and treat all instances as novel instances without knowing its mesh.
