### ISSUE TITLE
The difference between camera data and real data when scaling bbox

### ISSUE THREAD

**Issue by chenerg** [hughw19/NOCS_CVPR2019#12]
https://github.com/hughw19/NOCS_CVPR2019/blob/51df6183edbc4dbe96dc9cc1fd52692a5c5f44a5/dataset.py#L340-L359

For real data, you use `scale_factor[i, :] /= np.linalg.norm(scale_factor[i, :])`. For camera data, why not use the same manipulation?

**Comment by hughw19** [comment]
The CAMERA data are from ShapeNetCore, which are already normalized. No need for this normalization step.
