### ISSUE TITLE
How to generate my customized dataset?

### ISSUE THREAD

**Issue by zj-dong** [hughw19/NOCS_CVPR2019#14]
Hi He,

I am interested in the process of generating the synthetic data. Is it possible to provide the code to generate it from ShapeNet?

**Comment by zj-dong** [comment]
Which version of Shapnet are you using?

**Comment by haohlin** [comment]
Same here. Would be very helpful if someone can upload codes for that :)

**Comment by drsrinathsridhar** [comment]
The code for synthetic data generation is hard to setup outside of our machines since it requires extensive configuration in Unity. Implementing this is not hard, both ShapeNet and MS COCO are available, we just combine these two datasets.

**Comment by drsrinathsridhar** [comment]
We use ShapeNetCore v2.
