### ISSUE TITLE
Why flip z axis of coord map?

### ISSUE THREAD

**Issue by hankexin1314** [hughw19/NOCS_CVPR2019#16]
dataset.py line 335

coord_map = np.array(coord_map, dtype=np.float32) / 255
coord_map[:, :, 2] = 1 - coord_map[:, :, 2]

**Comment by Saafke** [comment]
@hankexin1314 @hughw19 I would also like to know the answer to this question.

**Comment by hughw19** [comment]
Originally, there are some discrepancies between the coordinate frames in the GT and in the vision system. I had to manually correct the discrepancy using this line of code. If you correctly render the NOCS GT by yourself, you may be able to avoid those ugly code.


Best,
He

**Comment by Saafke** [comment]
@hughw19 

Ok, I rendered the NOCS maps exactly like in the paper. I also have symmetrical objects (around the y-axis (this is the axis pointing up, as you use XZY coordinate system)), but for some reason, my NOCS predictions give the wrong colors (e.g. the object is completely red. I'll try removing that line! Are there any discrepancies I should be aware of?
