### ISSUE TITLE
Is depth information necessary?

### ISSUE THREAD

**Issue by icoric4** [hughw19/NOCS_CVPR2019#17]
Hi, really nice work! 

Have you maybe tried training a network for predicting the pose from NOCS map only, instead of using depth and Umeyama algorithm?

**Comment by drsrinathsridhar** [comment]
Hi there,

Sure, we can estimate camera pose without depth but this would not be metric---it would be in the NOCS space. We showed this in the supplementary material of the follow up paper:

https://geometry.stanford.edu/projects/xnocs/
