### ISSUE TITLE
How to get the model that used for NOCS ?

### ISSUE THREAD

**Issue by EasonEdison** [hughw19/NOCS_CVPR2019#18]
If I understand correctly，is the model used to create the NOCS a combination of all the camera models?
use all of camera models:

![image](https://user-images.githubusercontent.com/31425634/73328777-fb2fde00-4295-11ea-801a-a5c64c38dad6.png)

to create a model that used to create NOCS?

![image](https://user-images.githubusercontent.com/31425634/73328813-169ae900-4296-11ea-8f99-e7bd91910d85.png)

so, how to create this combined model?

[not this question ,I want to know how to get model ?](https://github.com/hughw19/NOCS_CVPR2019/issues/4)

**Comment by drsrinathsridhar** [comment]
No, it's not a combination of all the cameras. What you see above in NOCS is only one of the objects.
