### ISSUE TITLE
estimateSimilarityTransform function problem

### ISSUE THREAD

**Issue by hetolin** [hughw19/NOCS_CVPR2019#19]
Hi, I'm reading your code recently. I found that it is useful.  I wonder if I can use the `def estimateSimilarityTransform(source: np.array, target: np.array, verbose=False):` function to align NOCS Map and depth to get the GT pose？

**Comment by hughw19** [comment]
That is true. This function solves a Procruste problem with known correspondence, which is exactly the case in NOCS where we predict the NOCS value for each pixel. If you don’t have correspondence, this function will fail. 

Best,
He

**Comment by hetolin** [comment]
OK, I get it. Thank you very much for your reply.
