### ISSUE TITLE
Where is the Pre-trained weights

### ISSUE THREAD

**Issue by DemingWang** [hughw19/NOCS_CVPR2019#2]
Hi,
    I have some problem when running your code. It's mentioned in your ReadMe that the Pre-trained weight is provided. But I've not found. 
   Looking forward to your reply. Thank you.

**Comment by j96w** [comment]
Did anyone found the pre-trained weight? I cannot either.

**Comment by YfZeng** [comment]
If you mean mask_rcnn_coco.h5, here it is: https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5

**Comment by hughw19** [comment]
I just provided the download link for some pretrained weight in the README. Let me know if this solves your problem.

**Comment by DemingWang** [comment]
> I just provided the download link for some pretrained weight in the README. Let me know if this solves your problem.

Thanks a lot! The pretrained weights are helpful!
