### ISSUE TITLE
what's the camera intrinsics in synthetic data?

### ISSUE THREAD

**Issue by Guptajakala** [hughw19/NOCS_CVPR2019#22]
Thanks for the great work!
I'm doing a research project and may need to use your synthetic data. Can you tell me where can I find the camera intrinsics for both train and val split?

**Comment by hughw19** [comment]
Sorry for my late response. 
In detect_eval.py you can find:
intrinsics = np.array([[577.5, 0, 319.5], [0., 577.5, 239.5], [0., 0., 1.]])

**Comment by hughw19** [comment]
Hi Hoja,

Sorry for my late response. The information of camera intrinsics is in the https://github.com/hughw19/NOCS_CVPR2019/blob/master/detect_eval.py <https://github.com/hughw19/NOCS_CVPR2019/blob/master/detect_eval.py> file. Please take a look between line 171 and line 174.
