### ISSUE TITLE
How to use my own dataset for training?

### ISSUE THREAD

**Issue by palfonso01** [hughw19/NOCS_CVPR2019#23]
Hi,

Does anyone know how to generate NOCS (coord map) images? I have the color, depth, and mask images, but I'm missing the coord images on my own dataset. I will appreciate if anyone can give me a hint on this issue. It is not clear how to generate that kind of image.

Best,

Pedro

**Comment by hughw19** [comment]
Hi Pedro,

It truly depends on your renderer. With Blender, you can add a layer of material that has the same color value as the coordinate at each vertex. 

Best,
He

**Comment by palfonso01** [comment]
Hi He,

Thank you for your reply. I have my scene setup on Blender, so I'll try what you mentioned. 

Best,

Pedro

**Comment by Patlon** [comment]
> Hi He,
> 
> Thank you for your reply. I have my scene setup on Blender, so I'll try what you mentioned.
> 
> Best,
> 
> Pedro

Do you know how to generate NOCS (coord map) images using Blender? I also feel confuse aboute it.  I will appreciate if you can give me a hint on this issue.

**Comment by Patlon** [comment]
> you can add a layer of material that has the same color value as the coordinate at each vertex.

Hi, He
Do the coordinates at each vertex refer to  local coordinate or global coordinate？

**Comment by ran894694447** [comment]
@Patlon Hi, do you have a way to generate a coord image?
