### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'mode'

### ISSUE THREAD

**Issue by sunshantong** [hughw19/NOCS_CVPR2019#24]
Hi, thanks for your work.
When I run _python train.py_, the following happens

_Using TensorFlow backend.
Using GPU 0.
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    mode = args.mode
AttributeError: 'Namespace' object has no attribute 'mode'_

It seems that the mode attribute is not added to args. Can you give me some suggestions? Thank you very much.

**Comment by sunshantong** [comment]
I added _parser.add_argument('--mode', default='training', type=str, help="training/eval")_ on line 103 of _train.py_. This works, but I don't know if it's right.

**Comment by hughw19** [comment]
Thanks, Steve.

This is an old line of code and I should have deleted it while code cleaning. You can simply remove that line. I already update the train.py.


Best,
He
