### ISSUE TITLE
GT annotations for training data

### ISSUE THREAD

**Issue by t-walker-21** [hughw19/NOCS_CVPR2019#27]
Hello,

I am trying to evaluate other pose estimation methods using the NOCS dataset. I want to train with GT annotations, not using the coordinate space representation. I see GT annotations for validation and real test, but not for CAMERA train nor real train. Could you please provide the GT [R | T] for these sets or explain how that can be derived from NOCS + depth? Also, how can I go about unnormalizing the cad models of the CAMERA object? From my understanding, the .obj files have been bbox diagonal normalized. I need the real size of the objects.

Thanks

**Comment by hughw19** [comment]
For the GT annotation for CAMERA train and real train, you can use the aligning.py code I provided to convert GT NOCS to GT pose. It is quite accurate.

The GT alignment also contain the size/scale information.


Best,
He

**Comment by t-walker-21** [comment]
Thank you
