### ISSUE TITLE
Not found bbox_file

### ISSUE THREAD

**Issue by daichiono** [hughw19/NOCS_CVPR2019#3]
I've tried to run the train.py but bbox_file couldn't be found in dataset.py at line 392. For example, can_lotte_milk_norm.txt, camera_canon_wo_len_norm.txt, or laptop_alienware_norm.txt.
Where can I get these bbox_files or how can I create them?

And regarding this, how should I prepare the directory 'ShapeNetTOIModels/ShapeNetTOIFinalModels'?

**Comment by hughw19** [comment]
Hi Daichi,

Sorry for my late response. I just came back from my internship.

The repo is updated and you can download the object mesh and put the folder
under data/.

Let me know if this doesn’t work for you.


Best,
He
