### ISSUE TITLE
NOCS normalization

### ISSUE THREAD

**Issue by Saafke** [hughw19/NOCS_CVPR2019#30]
Hi, 

In the paper it says: 

> "Given a shape collection of known object CAD models for each category, we normalize their size by uniformly scaling the object such that the _diagonal_ of its tight bounding box has a length of 1 and is centered within the NOCS space (see Figure 2)."

Just to be sure, this _diagonal_ is the [**space diagonal**](https://en.wikipedia.org/wiki/Space_diagonal) of an object's tight bounding box right? (So, not a face diagonal.)

**Comment by hughw19** [comment]
Yes. It is the diagonal of the tight bounding box.



Best,
He
