### ISSUE TITLE
meta.txt confusion

### ISSUE THREAD

**Issue by Saafke** [hughw19/NOCS_CVPR2019#31]
Hi, 

Could you clear up some confusion I am having with the meta.txt files?

For example, val/0000/0000_meta.txt:

> 1 5 03642806 fdec2b8af5dd988cef56c22fd326c67
> 2 5 03642806 fae8d4929159d0df7d14ad32b7473fd2
> 3 1 02876657 e4915635a488cbfc4c3a35cee92bb95b
> 4 3 02942699 ee58b922bd93d01be4f112f1b3124b84
> 5 0 02992529 e3e43df4a3fc1870d4d7de9e3c2bb6f4
> 6 0 00000000 83ab18386e87bf4efef598dabc93c115
> 7 5 03642806 e9e28a11f71337fc201115f39f20d1ff
> 8 0 02992529 f75e6866c8965374f1c81a6df84170c9
> 9 1 02876657 ffa6c49aa8f7ec19971e7f8dbfabf375
> 10 0 00000000 fffc2fc5a90254de9e317a6cc797b629
> 11 0 02954340 f40b47fcbf83b962f0d11ae402ef940e
> 12 0 03211117 93e260150e7788ab574b5684eaec43e9
> 13 0 00000000 81bd0c7a35a147988cc3ae4061da3bb0
> 14 6 03797390 fd1f9e8add1fcbd123c841f9d5051936
> 15 0 02992529 df23ff3151aa1f0a3cb2f20e21cb06ff

Questions.

1. Is this correct?: first number = instance counter; second number = object class id; third number = shapenet class id; fourth 'number' = shapenet object id.

2. Why are there 16 lines? There are only four objects in the image. 

3. And for what is this meta_txt file necessary? Do I need to generate meta.txt files for my custom dataset?

(Extra question) 4. What is bbox.txt in the object folders? (I am guessing these are the object dimensions. The numbers are the distances from the centre point of the object measured in centimeters?)

**Comment by Guo-Ling** [comment]
Have you solved the problem？I have the same confusion with it, I would be very grateful if you could share your latest understanding of this issue.

**Comment by Uio96** [comment]
> Have you solved the problem？I have the same confusion with it, I would be very grateful if you could share your latest understanding of this issue.

#36 This issue might be helpful.
