### ISSUE TITLE
Question about Pose to NOCS

### ISSUE THREAD

**Issue by trevor-taeyeop** [hughw19/NOCS_CVPR2019#32]
Thanks for sharing the great work. 
I want to apply your method to a new dataset.
Can you share the code related pose(rotation,translation) to NOCS?? 
I would appreciate it if you could share the script you used to create this NOCS dataset.

Thanks in advances,

**Comment by hughw19** [comment]
What do you mean by "the code related pose(rotation, translation) to NOCS"?

Do you mean how I render the NOCS map?

**Comment by trevor-taeyeop** [comment]
Right! Could you share the nocs rendering process code?

**Comment by hughw19** [comment]
> Right! Could you share the nocs rendering process code?

I just added an example code for using Blender to render a NOCS map. You may want to take a look.

**Comment by peng25zhang** [comment]
@taeyeopl do you know how to render NOCS map with GT pose?
