### ISSUE TITLE
About Pose from Model Coordinate System to Camera Coordinate System

### ISSUE THREAD

**Issue by fylwen** [hughw19/NOCS_CVPR2019#33]
Hi. I'm trying to decompose the 'gt_RTs' provided in the groundtruth .pkl file into a **Rotation(R_m2c** with det(R_m2c)=1), **Scale(S_m** a diagnonal matrix with scaling factors for each axis, i.e., s_x, s_y, s_z>0) and **translation(t_m2c)**. 

Thus with these R_m2c, S_m, and t_m2c, I could transform the mesh **M**(.obj file) from its own object coordinate system(centered at the Origin) to the camera coordinate system by **R_m2c(S_m M)+t_m2c.**

However, I found that in order to get a reasonable result, I should flip the z-coordinate of the mesh M first, before I apply the transformation with R_m2c, S_m, t_m2c. Otherwise, the rendered result with the original M transformed by the decomposed 'gt_RTs'(shown as the picture with plain background) is different from the test images provided in the CAMERA dataset.
![test_render_00000](https://user-images.githubusercontent.com/48756873/95005169-32297100-0627-11eb-9666-a6d030e8559f.png)
![0000_color](https://user-images.githubusercontent.com/48756873/95005173-348bcb00-0627-11eb-9495-981a18a8eb58.png)
![test_render_00001](https://user-images.githubusercontent.com/48756873/95005172-33f33480-0627-11eb-8322-c1cd5add9af3.png)
![0001_color](https://user-images.githubusercontent.com/48756873/95005171-335a9e00-0627-11eb-952d-55ee3ef7807a.png)

Also, I notice that in  [ dataset.py, line 329](https://github.com/hughw19/NOCS_CVPR2019/blob/master/dataset.py#line329), you seem to flip the z-axis of the coordinate maps by computing 1-z, as the range of coordinate is in [0,1]. This shares a similarity with my observation. 

Thus, I'm wondering whether my observation is correct, that I should first flip the z-axis of the loaded .obj file, and then transform with gt_RTs to get a result consistent with the color images of the CAMERA dataset?

Thanks!

**Comment by hughw19** [comment]
Hi Frances,

Thanks for pointing it out. This is quite an old problem. It originates
from the left-handed coordinate system used in Blender, which we used for
rendering. When we uploaded the object model, we didn't pay attention to
this, which leads to a problem: all the objects are flipped from left to
right. You may observe some laptops with a flipped Windows desktop.

So, if you want to use our synthetic data, just flip your mesh. Or you can
generate your own synthetic data without this problem. Notice that we
didn’t use any CAD model for pose estimation, so it doesn’t affect us.



Best,
He

**Comment by hughw19** [comment]
*: uploaded  --> loaded
