### ISSUE TITLE
Question about how to generate the NOCS model

### ISSUE THREAD

**Issue by ziyedy** [hughw19/NOCS_CVPR2019#35]
Thanks for your sharing.
I have a question that I can not find the source code which uses to generate the NOCS model (.obj file), and I really don't understand the detail how to design and generate the NOCS model.
For example, I have no idea about how to generate a common camera model which can represent the category of Camera, and how can we get the NOCS value from this model.
Looking foward to your reply.

**Comment by hughw19** [comment]
I would suggest you go over the paper again. In NOCS, we don’t generate an
exemplar model for a category. Instead, the network learns to predict the
normalized coordinate, i.e. NOCS value, according to the true object shape.
Basically, NOCS value only differs from the true coordinate by a similarity
transformation (scale + 6D pose).

Best,
He

**Comment by WW-0** [comment]
请问作者，训练集里NOCS map的ground truth是怎么得到的

**Comment by hughw19** [comment]
I just added an example code for using Blender to render a NOCS map. You may want to take a look.

**Comment by hughw19** [comment]
> 请问作者，训练集里NOCS map的ground truth是怎么得到的

Please take a look at our paper. If your question is how ShapeNetCore model is normalized, the answer is they are already normalized as we described in the paper. Their original coordinates of each vertex, before you put the model into the scene, are NOCS ground truth.
