### ISSUE TITLE
Generate the normalized coordinate map

### ISSUE THREAD

**Issue by YoungXIAO13** [hughw19/NOCS_CVPR2019#4]
Hi He,
Can you tell me how to generate the normalized coordinate map as RGB image while rendering the 3D model?

**Comment by hjwdzh** [comment]
We used the custom shader in unity to render the synthetic data. Basically, we send the normalized object coordinate as part of the output in the vertex shader and input to the fragment shader. Then we output the coordinate as color in the fragment shader. Not sure whether that would be part of the release in the future though.

**Comment by YoungXIAO13** [comment]
> We used the custom shader in unity to render the synthetic data. Basically, we send the normalized object coordinate as part of the output in the vertex shader and input to the fragment shader. Then we output the coordinate as color in the fragment shader. Not sure whether that would be part of the release in the future though.

Thanks, I'm going to try it in blender : )

**Comment by YoungXIAO13** [comment]
Hi,

I've written a python script [here](https://github.com/YoungXIAO13/ObjectPoseEstimationDatasets/blob/a30acd083498107152167c8dd2a70f6f3067b0f8/blender_render/render_grid.py#L69) to generate normalized object coordinates as object materials in blender, which can be installed as a python package and easy to use.

You're welcome to check it out !
