### ISSUE TITLE
What is info.txt meaning for? 

### ISSUE THREAD

**Issue by densechen** [hughw19/NOCS_CVPR2019#5]
Hi, hughw,
Can you provide more details about the value stated in info.txt?
Thanks

**Comment by hughw19** [comment]
Can you specify which info.txt you refer to?

**Comment by LittleLampChen** [comment]
Hi, He
Thanks for providing the model obj file. 
For real sense, you have provided only the normalized model, but I can't figure out the scale of the normalized model. So, how can I get this scale factor?
What's more, you have provided three files for each real sense, (e.g. bottle_red_stanford_norm.obj, bottle_red_stanford_norm.txt, bottle_red_stanford_norm_vertices.txt). And I guess, the first file is the normalized obj model, and the third one is a .txt xyz file. However, I don't know what is the second file (bottle_red_stanford_norm.txt) meaning for?

Looking for your replay

**Comment by hughw19** [comment]
You can use RANSAC to solve for the object scale using ground truth NOCS map and depth image for any image you test. This is guaranteed to be correct.

The norm.txt specifies the scale of this object in its NOCS. Let's say the 3D tight bounding box of the mesh is a lx*ly*lz box. Then in its NOCS the scales will be (lx, ly, lz)/sqrt(lx**2+ly**2+lz**2) for each dimension. This can also be computed directly from the norm.obj.

**Comment by mentian** [comment]
Hi, He,
I tried to align the ground truth NOCS map with the corresponding depth image with your code. I got exactly same RTs with the label you provided in CAMERA val set, but slightly different RTs in Real test set. Is there any reason for this? Did you use different methods to get the labels for Real dataset?
Thanks.
