### ISSUE TITLE
What's the version of matplotlib  used in the code?

### ISSUE THREAD

**Issue by YanjieZe** [hughw19/NOCS_CVPR2019#50]
Hi, Mr.Wang

When I simply run the training code:
```shell
python train.py
```
 I encounter this problem:
```shell
from matplotlib.mlab import PCA
ImportError: cannot import name 'PCA'
```
My matplotlib's version is **3.3.4**.

I didn't see the package's version in README, and I have seached on stackoverflow but have no solution yet.
Could you provide matplotlib's version you use in this code, to let me know whether the problem comes from the version or something else?

Thanks in advance!!!

Y.J. Ze

**Comment by bf0724** [comment]
"from sklearn.decomposition import PCA"  replace "from matplotlib.mlab import PCA"
