### ISSUE TITLE
The link to the dataset seems to be unavailable

### ISSUE THREAD

**Issue by Fahrenheit200** [hughw19/NOCS_CVPR2019#59]
Where can I get the dataset? The link to the dataset here cannot be redirected normally.

**Comment by ldylab** [comment]
> Where can I get the dataset? The link to the dataset here cannot be redirected normally.

Hi, the link to the dataset is working(2021-11-05), you can right click and select "save link as..."

**Comment by Fahrenheit200** [comment]
> > Where can I get the dataset? The link to the dataset here cannot be redirected normally.
> 
> Hi, the link to the dataset is working(2021-11-05), you can right click and select "save link as..."

Thank you very much!
