### ISSUE TITLE
Why the RPN_ANCHOR_SCALES in train.py is different from the params in config.py

### ISSUE THREAD

**Issue by hankexin1314** [hughw19/NOCS_CVPR2019#6]
In train.py ScenesConfig  RPN_ANCHOR_SCALES=(16, 32, 48, 64, 128),
but in config.py RPN_ANCHOR_SCALES=(32, 64, 128, 256, 512)

**Comment by hughw19** [comment]
Hi Kexin,

The scales of RPN anchor boxes are adjustable depending on the image resolution and object scales on images. config.py is used for MaskRCNN on MS COCO dataset. I adjusted few parameters in ScenesConfig to fit my own datasets.

Hope this helps you.
