### ISSUE TITLE
Dataset links are unreachable

### ISSUE THREAD

**Issue by MaverickPeter** [hughw19/NOCS_CVPR2019#8]
Dataset links are unreachable.

**Comment by hughw19** [comment]
The server was unstable yesterday. You should be able to download it now.

**Comment by RobbyHuang** [comment]
Dataset links are still unreachable today except the training set of the CAMERA Dataset

**Comment by zj-dong** [comment]
I also can't download the dataset except the training set.

**Comment by hughw19** [comment]
@RobbyHuang @zj-dong 
I just tested the download links and all of them work well. This seems to be a problem raised by the web blocking in China. I already asked the network admin in our department for help. But, in case, you guys should be able to download it if you can get rid of the blocking in some ways.

**Comment by hughw19** [comment]
The admin have adjusted the download rate limit. Can anyone comment on whether those link are accessible now?

**Comment by zj-dong** [comment]
Now it works for me. Thank you!

**Comment by RobbyHuang** [comment]
I use IDM to download. And it works
